name: qasid
description: Personalized and self source control news app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.4+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependency_overrides:
  collection: ^1.15.0
  xml: ^5.4.1

dependencies:
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.1
  get_it: ^7.2.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  responsiveness:
    path: ./responsiveness
  shared_preferences: ^2.0.13
  webview_flutter: ^3.0.1
  xml: ^5.4.1
  share_plus: ^4.0.3
  theme:
    path: ./theme
  flutter_svg: ^1.1.1
  loading_animation_widget: ^1.2.0+2
  just_audio: ^0.9.27

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
